### ISSUE TITLE
Bug report: https://pnp.github.io/generator-teams/ dark mode toggle button seems odd

### ISSUE THREAD

**Issue by stephanbisser** [wictorwilen/generator-teams-tab#260]
### Description

The toggle button for the dark mode on https://pnp.github.io/generator-teams/ is a bit odd and should be fixed:

![image](https://user-images.githubusercontent.com/29750798/139254746-548ae85f-9b07-4a52-beb0-689090892403.png)

### Steps to reproduce

Navigate to https://pnp.github.io/generator-teams/ and use the toggle button in the nav bar

### Expected results

There should only be 1 toggle button not 2 😀

### Actual results

There are 2 buttons which need to be clicked to toggle between dark and normal mode

### Project you experience issues with

generator-teams

### generator version

-

### build tools version

-

### nodejs version

-

### npm version

-

### Operating system (environment)

Windows

**Comment by wictorwilen** [comment]
What browser? I only have one toggle in Edge.
![image](https://user-images.githubusercontent.com/5854279/139256784-0983a7d5-3133-487d-aead-6f4ddd7fca12.png)

**Comment by stephanbisser** [comment]
Edge Version 95.0.1020.30 (Official build) (64-bit)
But strange thing is that I only get that bug in one profile not all Edge profiles so maybe it's my client, let me check before investigating

**Comment by stephanbisser** [comment]
It was indeed my machine, so I'm closing this as it is now resolved 😀
